### ISSUE TITLE
An unexpected error occured.

### ISSUE THREAD

**Issue by nafeeur10** [Shopify/shopify-app-template-php#57]
```
X An unexpected error occured.
        To submit an issue include the stack trace.

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/system.rb:225:in `fetch': key not found: "PATHEXT" (KeyError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/system.rb:225:in `which'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/system.rb:219:in `resolve_path'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/context.rb:428:in `system'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/project_types/php/commands/serve.rb:35:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/project_types/php/commands/serve.rb:28:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/sub_command.rb:13:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/command.rb:19:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/core/monorail.rb:30:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/bin/shopify:37:in `block (2 levels) in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/bin/shopify:36:in `block in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.5/bin/shopify:47:in `<main>
```

After running `shopify php serve` giving this error!!

**Comment by Sanjay-100** [comment]
@nafeeur10   are you already login with Shopify ?

can you please provide me more step to reproduce the issue /
